<?php
$installer = $this;

$installer->startSetup();
$setup = new Mage_Eav_Model_Entity_Setup('core_setup');
$installer->run("
insert into {$this->getTable('core_email_template')} (`template_id`, `template_code`, `template_text`, `template_styles`, `template_type`, `template_subject`, `template_sender_name`, `template_sender_email`, `added_at`, `modified_at`, `orig_template_code`, `orig_template_variables`) values('8','Email for owner after confirm without access key','<body style=\"background:#F6F6F6; font-family:Verdana, Arial, Helvetica, sans-serif; font-size:12px; margin:0; padding:0;\">\r\n<div style=\"background:#F6F6F6; font-family:Verdana, Arial, Helvetica, sans-serif; font-size:12px; margin:0; padding:0;\">\r\n<table cellspacing=\"0\" cellpadding=\"0\" border=\"0\" height=\"100%\" width=\"100%\">\r\n    <tr>\r\n        <td align=\"center\" valign=\"top\" style=\"padding:20px 0 20px 0\">\r\n            <!-- [ header starts here] -->\r\n            <table bgcolor=\"FFFFFF\" cellspacing=\"0\" cellpadding=\"10\" border=\"0\" width=\"650\" style=\"border:1px solid #E0E0E0;\">\r\n                <tr>\r\n                    <td valign=\"top\">\r\n                        <a href=\"{{store url=\"\"}}\" style=\"color:#1E7EC8;\"><img src=\"{{var logo_url}}\" alt=\"{{var logo_alt}}\" border=\"0\"/></a>\r\n                    </td>\r\n                </tr>\r\n                <!-- [ middle starts here] -->\r\n                <tr>\r\n                    <td valign=\"top\">\r\n                        <p style=\"font-size:12px; line-height:16px; margin:0 0 16px 0;\">Hi {{var order.ownername}},<br/><br/>\r\n                            \r\n                            Your have successfully confirmed reservation for <a href=\"{{var order.spaceurl}}\" >{{var order.spacename}}</a> for user: {{var order.customername}}.\r\n                            <br>\r\n\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n                    <td bgcolor=\"#EAEAEA\" align=\"center\" style=\"background:#EAEAEA; text-align:center;\"><center><p style=\"font-size:12px; margin:0;\">Thank you</p></center></td>\r\n                </tr>\r\n            </table>\r\n        </td>\r\n    </tr>\r\n</table>\r\n</div>\r\n</body>','body,td { color:#2f2f2f; font:11px/1.35em Verdana, Arial, Helvetica, sans-serif; }','2','Reservation Confirmed Notification',NULL,NULL,'2014-06-18 11:28:19','2014-06-18 12:32:03',NULL,NULL);
insert into {$this->getTable('core_email_template')} (`template_id`, `template_code`, `template_text`, `template_styles`, `template_type`, `template_subject`, `template_sender_name`, `template_sender_email`, `added_at`, `modified_at`, `orig_template_code`, `orig_template_variables`) values('9','Email for renter after confirm without access key','<body style=\"background:#F6F6F6; font-family:Verdana, Arial, Helvetica, sans-serif; font-size:12px; margin:0; padding:0;\">\r\n<div style=\"background:#F6F6F6; font-family:Verdana, Arial, Helvetica, sans-serif; font-size:12px; margin:0; padding:0;\">\r\n<table cellspacing=\"0\" cellpadding=\"0\" border=\"0\" height=\"100%\" width=\"100%\">\r\n    <tr>\r\n        <td align=\"center\" valign=\"top\" style=\"padding:20px 0 20px 0\">\r\n            <!-- [ header starts here] -->\r\n            <table bgcolor=\"FFFFFF\" cellspacing=\"0\" cellpadding=\"10\" border=\"0\" width=\"650\" style=\"border:1px solid #E0E0E0;\">\r\n                <tr>\r\n                    <td valign=\"top\">\r\n                        <a href=\"{{store url=\"\"}}\" style=\"color:#1E7EC8;\"><img src=\"{{var logo_url}}\" alt=\"{{var logo_alt}}\" border=\"0\"/></a>\r\n                    </td>\r\n                </tr>\r\n                <!-- [ middle starts here] -->\r\n                <tr>\r\n                    <td valign=\"top\">\r\n                        <p style=\"font-size:12px; line-height:16px; margin:0 0 16px 0;\">Congratulations, {{var order.customername}}!<br/><br/>\r\n                            \r\n                            Your reservation for <a href=\"{{var order.spaceurl}}\" >{{var order.spacename}}</a> has been confirmed by owner: {{var order.ownername}}.\r\n                            <br>\r\n                        \r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n                    <td bgcolor=\"#EAEAEA\" align=\"center\" style=\"background:#EAEAEA; text-align:center;\"><center><p style=\"font-size:12px; margin:0;\">Thank you</p></center></td>\r\n                </tr>\r\n            </table>\r\n        </td>\r\n    </tr>\r\n</table>\r\n</div>\r\n</body>','body,td { color:#2f2f2f; font:11px/1.35em Verdana, Arial, Helvetica, sans-serif; }','2','Congratulations',NULL,NULL,'2014-06-18 11:53:46','2014-06-18 12:32:36',NULL,NULL);
");
$installer->endSetup();