
<div class="my-account">
<div class="page-title">
    <h1 class="arrowbubble"> <b class="icon_grid sentmail_id "></b> <?php echo $this->__('Email Inbox');?></h1>
</div>

<?php
    $messageTypes = array(
        'new_order_to_renter'=>'sales_email/order/template',
        'new_order_to_owner' => 'sales_email/owner/template',
        'after_cancel_to_owner' => 'sales_email/after_cenceled_for_owner/template',
        'after_cancel_to_renter' => 'sales_email/after_cenceled_for_renter/template',
        'after_confirm_to_renter_with_access_code' => 'sales_email/after_confirmed_for_renter/template',
        'after_confirm_to_owner_with_access_code' => 'sales_email/after_confirmed_for_owner/template',
        'after_confirm_to_renter_without_access_code' => 'sales_email/after_confirm_to_renter_without_access_key/template',
        'after_confirm_to_owner_without_access_code' => 'sales_email/after_confirm_to_owner_without_access_key/template',
    );
/* 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
$inboxDetails = Mage::getModel('airhotels/airhotels')->getInboxDetails();
//echo "<pre>";var_dump($inboxDetails);die();

if(count($inboxDetails)){
    ?>
    <form name="mailform" action="" method="post" id="mailin">
	    <div id="inboxSpace">
                <div class="innerpage_btn left" style="line-height: 26px;margin-left: 10px;" onclick="confirmDelete()" ><?php echo $this->__('Delete'); ?></div>
	        <table class="inboxTable" id="outboxList">
	            <?php
                $storeName = Mage::getStoreConfig('general/store_information/name');
                for($i=0;$i<count($inboxDetails);$i++ ){ ?>
	            <?php 
                    $customer_id = Mage::getSingleton('customer/session')->getCustomer()->getId();
                    $receiver_id = $inboxDetails[$i]["receiver_id"]; 
                    if ($customer_id == $receiver_id) {
            if ($inboxDetails[$i]["receiver_read"] == '1') {
                $read_class = "class='read'";
            } else {
                $read_class = "class='unread' ";
            }
        } else {
            if ($inboxDetails[$i]["sender_read"] == '1') {
                $read_class = "class='read'";
            } else {
                $read_class = "class='unread' ";
            }
        }
          
                    ?>
                    <tr style="cursor: pointer" <?php 
                    echo $read_class; ?>  onclick="this.className ='read' ">
	                <td><input type="checkbox" style="margin-left: 5px" name="messageid[]" value="<?php echo $inboxDetails[$i]["message_id"]; ?>" id="checkinbox"/></td>
	                <td onclick="openMessage(1,'<?php echo $inboxDetails[$i]["message_id"]; ?>')">
	                    <?php echo $this->__('From'); ?> : <?php  $customer = Mage::getModel('customer/customer')->load($inboxDetails[$i]["sender_id"]); echo ucfirst($inboxDetails[$i]["message_type"] == null ? $customer->getName():$storeName);

                            $replycount = Mage::getModel('airhotels/airhotels')->getReplyCount($inboxDetails[$i]["message_id"]);
                           
                            if($replycount["count"]):
                                echo " ".$this->__("Re").":"."(".$replycount["count"].")";
                            endif;

                            ?>
	                </td>
	                <td onclick="openMessage(1,'<?php echo $inboxDetails[$i]["message_id"]; ?>')">
	                    <?php
                        if ($inboxDetails[$i]["order_id"] !=  '0') {
                            $emailTemplateId = Mage::getStoreConfig($messageTypes[$inboxDetails[$i]["message_type"]]);
                            $orderId= $inboxDetails[$i]["order_id"];
                            $order = Mage::getModel('sales/order')->loadByIncrementId($orderId);
                            $paymentBlock = Mage::helper('payment')->getInfoBlock($order->getPayment())
                                ->setIsSecureMode(true);
                            $paymentBlock->getMethod();
                            $paymentBlockHtml = $paymentBlock->toHtml();
                            // set template variables
                            $templateVariables = array();
                            $templateVariables['order'] = $order;
                            $templateVariables['billing'] = $order->getBillingAddress();
                            $templateVariables['payment_html'] = $paymentBlockHtml;
                            $savedVariables = unserialize($inboxDetails[0]["message"]);
                            foreach ($savedVariables['order'] as $key => $value) {
                                $templateVariables['order'][$key] = $value;
                            }
                            foreach ($savedVariables['custom'] as $key => $value) {
                                $templateVariables[$key] = $value;
                            }
                            $sTemplate = Mage::getModel('core/email_template')
                                ->load($emailTemplateId)
                                ->getProcessedTemplate($templateVariables);
                            $doc = new DOMDocument;
                            @$doc->loadHTML($sTemplate);
                            $xpath = new DOMXPath($doc);
                            $text = '';
                            foreach ($xpath->query('//body') as $div) {
                                $text .= $div->textContent;
                            }
                            echo mb_substr(trim($text),0,100).'..';
                        }else{
                            echo (strlen($inboxDetails[$i]["message"])>30)? substr($inboxDetails[$i]["message"],0,30) : $inboxDetails[$i]["message"]."..";
                        }
                        ?>
                          
	                </td>
	                <td onclick="openMessage(1,'<?php echo $inboxDetails[$i]["message_id"]; ?>')">
	                    <?php echo date("d/m/Y",strtotime ($inboxDetails[$i]["created_date"]) );  ?>
	                </td>
	            </tr>
	            <?php  } ?>
	        </table>
	    </div>
    </form>
    <div id="mailSpace" style="display: none"></div>
   
        <?php
}
else{
    ?>
    <h1 class="no_mails">
    <?php echo $this->__('No mails received'); ?>
    </h1>
    <?php
}
?>
    <div class="clear"></div>
     </div>
<script type="text/javascript">
        function openMessage(flag,messageId){
            if(flag==1){
                document.getElementById("inboxSpace").style.display = "none";
                document.getElementById("mailSpace").style.display = "block";
                getMessageDetails(messageId);
            }
            else{
                document.getElementById("inboxSpace").style.display = "block";
                document.getElementById("ReplyMail").style.display = "none";
                document.getElementById("mailSpace").style.display = "none";
            }
        }
        function getMessageDetails(messageId){
            var xmlhttp = getHttp();
            document.getElementById("mailSpace").innerHTML="<div style='margin:50px 0px 50px 0px; text-align:center;' ><img  src='<?php echo $this->getSkinUrl('images/loading1.gif') ?>' /></div>";
            xmlhttp.onreadystatechange=function()
            {
                if (xmlhttp.readyState==4 && xmlhttp.status==200)
                {
                    document.getElementById("mailSpace").innerHTML=xmlhttp.responseText;
                    updateUnreadMsgDisplay();
                }
            }
            var url = "<?php echo Mage::getBaseUrl() . 'booking/property/showmessage/' ?>";
            url=url+"id/"+messageId+"/show/in";
            xmlhttp.open("GET",url,true);
            xmlhttp.send();
        }

        function updateUnreadMsgDisplay(){
            var url = "<?php echo Mage::getBaseUrl() . 'booking/property/getUnreadMsgCount' ?>";

            jQuery.ajax({
                url:url,
                success:function(data){
                    jQuery('.unread-msg-count').text(data);
                }
            })
        }
        function getHttp(){
            var xmlhttp;
            if (window.XMLHttpRequest)
            {// code for IE7+, Firefox, Chrome, Opera, Safari
                xmlhttp=new XMLHttpRequest();
            }
            else
            {// code for IE6, IE5
                xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
            }
            return xmlhttp;
        }
        function confirmDelete(){
            
            //alert(jQuery("input:checked").length);
            //return false;
            if(jQuery("input:checked").length != ""){
            if(confirm("<?php echo $this->__('Are you sure want to delete'); ?>")){
                document.mailform.submit();
                return true;
            }
           }
            else{
                confirm("<?php echo $this->__('Please select the checkbox to delete'); ?>");
                return false;
            }
        }
        function validateReply(){
            if(jQuery.trim(document.getElementById("replyMessage").value).length==0){
                alert("<?php echo $this->__('Please fill message'); ?>");
            }
            else{
                document.reply.submit();
            }
        }
</script>
