
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places&amp;sensor=false"></script>
<script type="text/javascript">
    function initialize() {
        var mapOptions = {
            //center: new google.maps.LatLng(-33.8688, 151.2195),
            zoom: 13,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById('map_canvas'),
        mapOptions);

        var input = document.getElementById('searchTextField');
        var autocomplete = new google.maps.places.Autocomplete(input);

        autocomplete.bindTo('bounds', map);
        // Autocomplete.
        function setupClickListener(id, types) {
            var radioButton = document.getElementById(id);
            google.maps.event.addDomListener(radioButton, 'click', function() {
                autocomplete.setTypes(types);
            });
        }

    }
    google.maps.event.addDomListener(window, 'load', initialize);
</script>

<?php
$count = 1;
$twoDiv = 1;
$model = Mage::getModel('catalog/product');
$baseurl = Mage::getBaseUrl('skin');


$_productCollection = Mage::getModel('airhotels/property')->getpropertycollection()
                ->addAttributeToFilter('status', array('eq' => 1))
                ->addAttributeToFilter('propertyapproved',array('eq' => 1)) 
                ->setPageSize(10)->setOrder('created_at', 'desc')->addAttributeToSelect('*');
$currencySymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
if(count($_productCollection)!= 0){

?>
<ul>

<?php
foreach($_productCollection as $product){   
    
$customerData = Mage::getModel('airhotels/airhotels')->getCustomerPictureById($product->getUserid());
$customer = Mage::getModel('customer/customer')->load($product->getUserid());
if($twoDiv <= 2){?>
<li class="res_list home-medium-dealbox<?php echo $twoDiv ?>">
<div class="popular_2up_listings_view">
    <div class="row2-wishlists-list clearfix">
        <div class="wishlists2-list-item twospace_list">
             <?php
                                $homemedium=$this->helper('catalog/image')->init($product, 'image')
                                ->constrainOnly(TRUE)
                                ->keepAspectRatio(TRUE)
                                ->keepFrame(FALSE)
                                ->resize(460,null)
                            ?>
            <a href="<?php echo $this->helper('wishlist')->getAddUrl($product) ?>" class="wish_list_button link-cart" title="Save this listing to review later"  > <span class="icon"></span> </a>
            <a href="<?php echo Mage::getBaseUrl() . $product->getUrlPath(); ?>" class="matte2-media-box">
                <img alt="<?php echo substr($product->getName(), 0, 25); ?>" src="<?php if ($product->getImage() != 'no_selection') {
                                    echo $homemedium;
                                    } else {
                                    echo $product->getImageUrl();
                               }?>" 
                         width ="460" height="255" title="<?php echo substr($product->getName(), 0, 25); ?>" >         
                
            </a>
            
            <div class="feed_item_view">
                    <div class="floatleft">
                        <a href="<?php echo Mage::getBaseUrl() . $product->getUrlPath(); ?>" >
                            <span class="h4"><?php echo substr($product->getName(), 0, 25); ?></span>
                        <span><?php echo $product->getState().','. $product->getCountry(); ?></span></a> 
                    </div>
                    <div class="popular_price">
                        <a href="<?php echo Mage::getBaseUrl() . $product->getUrlPath(); ?>" >
                        <span class="price-tag-price">
                         <?php
                         echo $currencySymbol . round(Mage::helper('directory')->currencyConvert($product['Price'], Mage::app()->getStore()->getBaseCurrencyCode(), Mage::app()->getStore()->getCurrentCurrencyCode()), 0);?>
                        </span>
                            
                        <span class="price-tag-price-pernight"><?php echo $this->__('Per Night'); ?></span>
                        </a>
                    </div>
                </div>
        </div>
</div>
    </div>
</li>
<?php
   if($twoDiv == 2){
       echo '<li class="clear"></li>';
       $twoDiv = 1;
   }  else {
  	$twoDiv = 2;
   }
        }?>
     
     
   <?php 
    if($count == 6){
       break;
   }
   
   $count = $count+1;
  
   }
} else {
    echo '<div class="clear"></div>';
}
    ?>
</ul>

<script type="text/javascript">
    var $slide = jQuery.noConflict();
    function showTabs(id,menuName){
        $slide(".main_content").hide();
        $slide(".main_link").removeClass("selected");
        $slide("#"+menuName).addClass("selected");
        $slide("#"+id).show();
    }
</script>

