<script type="text/javascript">
    function initialize() {
        var mapOptions = {
            //center: new google.maps.LatLng(-33.8688, 151.2195),
            zoom: 13,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById('map_canvas'),
        mapOptions);

        var input = document.getElementById('searchTextField');

        var autocomplete = new google.maps.places.Autocomplete(input);

        autocomplete.bindTo('bounds', map);
        // Autocomplete.
        function setupClickListener(id, types) {
            var radioButton = document.getElementById(id);
            google.maps.event.addDomListener(radioButton, 'click', function() {
                autocomplete.setTypes(types);
            });
        }

    }
    google.maps.event.addDomListener(window, 'load', initialize);
    var $s = jQuery.noConflict();
    function validateSearch(){
        $s("#searchResult").html("");
        $s("#searchTextField").css("border-color","#D2D2D2");
        window.location.href = "<?php echo Mage::getBaseUrl() . 'booking/property/advsearch/' ?>";
        $s("#searchResult").html("Please set location");
        return true;
    }
      
        var jQ = jQuery.noConflict();
            jQ(function() {
   
                    var dates = jQ( "#checkinDate, #checkinTo" ).datepicker({
                            //defaultDate: "+1w",
                            changeMonth: true,
                            numberOfMonths: 1,
                            minDate: '0',
                            onSelect: function( selectedDate ) {
                                    var option = this.id == "checkinDate" ? "minDate" : "maxDate",
                                            instance = jQ( this ).data( "datepicker" ),
                                            date = jQ.datepicker.parseDate(
                                                    instance.settings.dateFormat ||
                                                    jQ.datepicker._defaults.dateFormat,
                                                    selectedDate, instance.settings );
                                    dates.not( this ).datepicker( "option", option, date );
                                    jQ("#checkinDate" ).datepicker("option","maxDate","");

                                    if(this.id == "checkinDate"){
                                            instance = jQ( this ).data( "datepicker" )
                                            var depart = jQ.datepicker.parseDate(jQ.datepicker._defaults.dateFormat, selectedDate);
                                            depart.setDate(depart.getDate() + 1);
                                            jQ("#checkinTo" ).datepicker(  "option", "minDate", depart );
                                    }
                            }
                    });
            });

       
        </script>



        <script type="text/javascript">
            
   var myWidth;
if( typeof( window.innerWidth ) == 'number' ) {
    //Non-IE
    myWidth = window.innerWidth;
}

 var $doc = jQuery.noConflict();
$doc(function () {

      // Slideshow 1
      $doc(".rslides1").responsiveSlides({
        speed: 1000,
        nav: true,
        namespace: "callbacks",
        maxwidth: myWidth
      });    

    });
  </script>
<div class="responsive-container"> 
    <iframe src="http://player.vimeo.com/video/66514891" height="360" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
</div>
  
  
  
